# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.
set(AWSSDK_PLATFORM_DEPS_LIBS pthread)
set(AWSSDK_CLIENT_LIBS curl)
set(AWSSDK_CRYPTO_LIBS )
set(AWSSDK_CRYPTO_IN_SOURCE_BUILD )
set(AWSSDK_COMMON_RUNTIME_LIBS aws-crt-cpp;aws-c-http;aws-c-mqtt;aws-c-cal;aws-c-auth;aws-c-common;aws-c-io;aws-checksums;aws-c-event-stream;aws-c-s3;aws-c-compression;aws-c-sdkutils)
set(AWSSDK_ADDITIONAL_LIBS )
set(AWSSDK_INSTALL_LIBDIR lib64)
set(AWSSDK_INSTALL_BINDIR bin)
set(AWSSDK_INSTALL_INCLUDEDIR include)
set(AWSSDK_INSTALL_ARCHIVEDIR bin)
if (NOT LibCrypto_INCLUDE_DIR)
    set(LibCrypto_INCLUDE_DIR /usr/include CACHE INTERNAL "The OpenSSL include directory")
endif()
if (NOT LibCrypto_STATIC_LIBRARY)
    set(LibCrypto_STATIC_LIBRARY /usr/lib64/libcrypto.so CACHE INTERNAL "The OpenSSL crypto static library")
endif()
if (NOT LibCrypto_SHARED_LIBRARY)
    set(LibCrypto_SHARED_LIBRARY /usr/lib64/libcrypto.so CACHE INTERNAL "The OpenSSL crypto shared library")
endif()
